global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - localhost:9090

  - job_name: "api-gateway"
    # one target per running copy
    dns_sd_configs:
      - names: ["api-gateway"]
        type: A
        port: 5000

  - job_name: "user-service"
    static_configs:
      - targets:
          - user-service:5001

  - job_name: "hackathon-service"
    # one target per running copy
    dns_sd_configs:
      - names: ["hackathon-service"]
        type: A
        port: 5002

  - job_name: "admin-service"
    static_configs:
      - targets:
          - admin-service:5006

  - job_name: "media-service"
    static_configs:
      - targets:
          - media-service:5003

  - job_name: "notification-service"
    static_configs:
      - targets:
          - notification-service:5004

  - job_name: "chatbot-service"
    static_configs:
      - targets:
          - chatbot-service:5005